name: 'snowflake_handson'  # プロジェクト名
profile: 'default'  # どの接続profileを使うか
model-paths: ["models"]  # モデルはmodelsフォルダ、の宣言
macro-paths: ["macros"]  # 以下、各種フォルダの場所


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  staging:
      +database: STAGING  # このレイヤーは STAGING データベースに作る
      +materialized: table
      +tags: ["layer_staging"]  # このフォルダのモデル全部に layer_staging タグを付与
      +persist_docs:  # 説明文をSnowflake側にも反映（下で解説）
        relation: true  # テーブル/ビューの説明をSnowflakeに反映
        columns: true  # カラムの説明も反映
      handson:
        +schema: HANDSON

